---
- name: hdc tuning
  hosts: cdh-dev
  remote_user: root

  tasks:
    - name: change swappiness
      shell: "{{item}}"
      with_items:
        - echo 10 > /proc/sys/vm/swappiness
        - echo 'vm.swappiness = 10' >> /etc/sysctl.conf

    - name: change defrag
      shell: "{{item}}"
      with_items:
        - echo never > /sys/kernel/mm/transparent_hugepage/defrag
        - echo 'echo never > /sys/kernel/mm/transparent_hugepage/defrag' >> /etc/rc.local

